server.port=8081

# Conexão com o SQL Server via Autenticação do Windows (Integrated Security)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=biblioteca_comunitaria;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Deixe o usuário e senha vazios pois usará as credenciais do Windows
spring.datasource.username=root
spring.datasource.password=root

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true